# Generated by Django 3.2.6 on 2021-08-25 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20210825_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='StaffProfileID',
        ),
    ]
