# Generated by Django 3.2.6 on 2021-08-25 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_staff_staffprofileid'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='StaffProfileID',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='account.staffprofile'),
        ),
    ]
