# Generated by Django 3.2.6 on 2021-08-30 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_staff_staffprofileid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='StaffProfileID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.staffprofile'),
        ),
    ]
