# Generated by Django 3.2.6 on 2021-08-30 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='Client',
            new_name='ClientID',
        ),
    ]
