# Generated by Django 3.2.6 on 2021-08-25 09:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contract', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventStatut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateCreated', models.DateTimeField(auto_now_add=True)),
                ('DateUpdated', models.DateTimeField(auto_now=True)),
                ('Attendees', models.IntegerField()),
                ('EventDate', models.DateTimeField()),
                ('Notes', models.TextField(blank=True, max_length=8192)),
                ('ContractID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract.contract')),
                ('EventStatutID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.eventstatut')),
                ('SupportContactID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
